
name: Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

defaults:
    run:
      working-directory: ./terraform

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with: 
        terraform_version: "1.9.5" 
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: '${{ secrets.ROLE_ARN }}'
        role-session-name: github-actions-session
        aws-region: eu-west-2

    - name: Terraform validate
      run: |
        terraform init
        terraform fmt -check
        terraform validate

    - name: Linting 
      uses: terraform-linters/setup-tflint@v4
    - run: |
       tflint --init
       tflint

    - name: Checkov Scan
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      with: 
        directory: ./terraform
        check: CKV_AWS_1,CKV_AWS_2,CKV_AWS_41
        soft_fail: true

    - name: Terraform Apply
      run: |
          terraform plan
          terraform apply -auto-approve
    
    - name: Wait for EKS Cluster 
      run: |
          aws eks wait cluster-active --name eks-cluster --region eu-west-2
  
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region eu-west-2 --name eks-cluster
        kubectl wait --for=condition=Ready nodes --all --timeout=300s
        kubectl apply -f ./cert-man/issuer.yaml
